version: '3.8'

services:
  # Interactive Brokers Gateway
  ibgw:
    image: ghcr.io/waytrade/ib-gateway-docker:latest
    restart: unless-stopped
    environment:
      - TWS_USERID=${IB_USERNAME}
      - TWS_PASSWORD=${IB_PASSWORD}
      - TRADING_MODE=paper  # Change to 'live' for production
      - VNC_SERVER_PASSWORD=${VNC_PASSWORD:-ib}
    ports:
      - "7497:7497"  # TWS API port for paper trading
      - "7496:7496"  # TWS API port for live trading
      - "5900:5900"  # VNC server port

  # PostgreSQL with TimescaleDB extension
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-turingtrader}
    volumes:
      - timescale_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Redis for caching
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis} --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  # TuringTrader application
  turingtrader:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - MODE=${TRADING_MODE:-paper}
      - RISK_LEVEL=${RISK_LEVEL:-5}
      - POSTGRES_HOST=timescaledb
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-turingtrader}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis}
      - IB_HOST=ibgw
      - IB_PORT=7497  # Use 7496 for live trading
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
      - ./config.ini:/app/config.ini
    depends_on:
      - ibgw
      - timescaledb
      - redis

  # Monitoring Dashboard
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=timescaledb
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-turingtrader}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis}
    ports:
      - "8050:8050"
    depends_on:
      - turingtrader
      - timescaledb
      - redis

volumes:
  timescale_data:
  redis_data: